name: ci-cd-check
on:
    push:
        branches:
            - main
jobs:
    continuousintegration_CI:
        name: Continuous integration test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v4

            - name: Install node js
              uses: actions/setup-node@v4
              with:
                node-version: '18'
            - name: install dependencies
              run: npm ci
            - name: Run build command
              run: npm run build
            - name: Run test cases
              run: npm run tests | true
              
              

            

        

