name: test-ci-cd-pipeline
on:
    push:
        branches:
            - main
jobs:
    check-ci:
        name: Check Continuous integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Install node js
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci

            - name: Take build
              run: npm run build

            - name: Run tests
              run: npm run test || echo "No test cases found"
    build-images:
        name: build docker image now
        needs: check-ci
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: create docker image here
              run: |
                docker build -t ci-cd-poc-test .

              

            