name: CI-CD pipeline execution
on:
  push:
    branches:
      - main
jobs:
  ci-integration:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the code
        uses: actions/checkout@v4
      
      - name: install node js
        uses: actions/setup-node@v6
        with:
          node-version: 20
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run the application build
        uses: npm run build
      
      - name: Run the test cases
        uses: npm run test

      
